### ISSUE TITLE
Fatal Error on $ composer require aschmelyun/fleet

### ISSUE THREAD

**Issue by teampl4y4** [aschmelyun/fleet#5]
I am running php 8.1, and when I run:

`$ composer require aschmelyun/fleet`

I get this output:
```
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Console\Helper\mb_detect_encoding() in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:50
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/Helper.php(123): Symfony\Component\Console\Helper\Helper::strlen()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(489): Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration()
#2 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(561): Symfony\Component\Console\Helper\ProgressBar::Symfony\Component\Console\Helper\{closure}()
#3 [internal function]: Symfony\Component\Console\Helper\ProgressBar->Symfony\Component\Console\Helper\{closure}()
#4 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(574): preg_replace_callback()
#5 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(393): Symfony\Component\Console\Helper\ProgressBar->buildLine()
#6 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(302): Symfony\Component\Console\Helper\ProgressBar->display()
#7 /usr/share/php/Composer/Util/Loop.php(85): Symfony\Component\Console\Helper\ProgressBar->start()
#8 /usr/share/php/Composer/Installer/InstallationManager.php(454): Composer\Util\Loop->wait()
#9 /usr/share/php/Composer/Installer/InstallationManager.php(339): Composer\Installer\InstallationManager->waitOnPromises()
#10 /usr/share/php/Composer/Installer/InstallationManager.php(266): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#11 /usr/share/php/Composer/Installer.php(698): Composer\Installer\InstallationManager->execute()
#12 /usr/share/php/Composer/Installer.php(535): Composer\Installer->doInstall()
#13 /usr/share/php/Composer/Installer.php(247): Composer\Installer->doUpdate()
#14 /usr/share/php/Composer/Command/RequireCommand.php(323): Composer\Installer->run()
#15 /usr/share/php/Composer/Command/RequireCommand.php(243): Composer\Command\RequireCommand->doUpdate()
#16 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Composer\Command\RequireCommand->execute()
#17 /usr/share/php/Symfony/Component/Console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#18 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#19 /usr/share/php/Composer/Console/Application.php(310): Symfony\Component\Console\Application->doRun()
#20 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#21 /usr/share/php/Composer/Console/Application.php(122): Symfony\Component\Console\Application->run()
#22 /usr/bin/composer(64): Composer\Console\Application->run()
#23 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 50

Fatal error: Uncaught Error: Call to undefined function Symfony\Component\Console\Helper\mb_detect_encoding() in /usr/share/php/Symfony/Component/Console/Helper/Helper.php:50
Stack trace:
#0 /usr/share/php/Symfony/Component/Console/Helper/Helper.php(123): Symfony\Component\Console\Helper\Helper::strlen()
#1 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(489): Symfony\Component\Console\Helper\Helper::strlenWithoutDecoration()
#2 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(561): Symfony\Component\Console\Helper\ProgressBar::Symfony\Component\Console\Helper\{closure}()
#3 [internal function]: Symfony\Component\Console\Helper\ProgressBar->Symfony\Component\Console\Helper\{closure}()
#4 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(574): preg_replace_callback()
#5 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(393): Symfony\Component\Console\Helper\ProgressBar->buildLine()
#6 /usr/share/php/Symfony/Component/Console/Helper/ProgressBar.php(302): Symfony\Component\Console\Helper\ProgressBar->display()
#7 /usr/share/php/Composer/Util/Loop.php(85): Symfony\Component\Console\Helper\ProgressBar->start()
#8 /usr/share/php/Composer/Installer/InstallationManager.php(454): Composer\Util\Loop->wait()
#9 /usr/share/php/Composer/Installer/InstallationManager.php(339): Composer\Installer\InstallationManager->waitOnPromises()
#10 /usr/share/php/Composer/Installer/InstallationManager.php(266): Composer\Installer\InstallationManager->downloadAndExecuteBatch()
#11 /usr/share/php/Composer/Installer.php(698): Composer\Installer\InstallationManager->execute()
#12 /usr/share/php/Composer/Installer.php(535): Composer\Installer->doInstall()
#13 /usr/share/php/Composer/Installer.php(247): Composer\Installer->doUpdate()
#14 /usr/share/php/Composer/Command/RequireCommand.php(323): Composer\Installer->run()
#15 /usr/share/php/Composer/Command/RequireCommand.php(243): Composer\Command\RequireCommand->doUpdate()
#16 /usr/share/php/Symfony/Component/Console/Command/Command.php(255): Composer\Command\RequireCommand->execute()
#17 /usr/share/php/Symfony/Component/Console/Application.php(1009): Symfony\Component\Console\Command\Command->run()
#18 /usr/share/php/Symfony/Component/Console/Application.php(273): Symfony\Component\Console\Application->doRunCommand()
#19 /usr/share/php/Composer/Console/Application.php(310): Symfony\Component\Console\Application->doRun()
#20 /usr/share/php/Symfony/Component/Console/Application.php(149): Composer\Console\Application->doRun()
#21 /usr/share/php/Composer/Console/Application.php(122): Symfony\Component\Console\Application->run()
#22 /usr/bin/composer(64): Composer\Console\Application->run()
#23 {main}
  thrown in /usr/share/php/Symfony/Component/Console/Helper/Helper.php on line 50
```

**Comment by teampl4y4** [comment]
Was missing mbstring php extension.
